spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: create-drop

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
port: 8080
