package br.com.luiz.locbem.model.offer;

public enum TipoVeiculo {
    AUTOMOVEL_DE_PASSAGEIROS,
    SUV,
    CAMINHAO,
    VAN_MINIVAN,
    MOTOCICLETA,
    BICICLETA_MOTORIZADA,
    VEICULO_ELETRICO,
    ONIBUS,
    CAMINHAO_DE_ENTREGA,
    VEICULO_DE_RECREACAO,
    VEICULO_TODO_TERRENO,
    VEICULO_AQUATICO,
    AERONAVE_LEVE,
    VEICULO_FERROVIARIO
}
